print("visual에서 수정 후 github에 수정본 보내는 법")
print("1. 수정 파일 visual에 있는 터미널에 git add . 작성.")
print("2. git status 로 수정된 파일 확인.")
print("3. git commit -m "second commit"  작성.")
print("(여기서 큰 따옴표 안에는 히스토리 이름을 작성 ex> 세번 째 파일일 경우: third commit)")
print("4. git push origin master 를 작성.")
print("==> visual에 작성한 코드 github으로 보내기 성공")
